version: "3.9"
services:
  testing:
    build:
      context: .
      target: testing
    env_file:
      - ./.env.test
  web:
    build:
      context: .
      target: production
    ports:
      - "5000:5000"
    env_file:
      - ./.env
